// Instructor-provided testing program.

import java.io.File;
import java.io.FileNotFoundException;
import java.util.LinkedList;
import java.util.List;
import java.util.Random;
import java.util.Scanner;

/**
 * Class DodgeballMain is the main client program for
 * dodgeball management. It reads names from a file
 * dodgeball.txt, shuffles them, and uses them to start the
 * game. The user is asked for the thrower's target action (name of a person),
 *  then whether the throw was a hit (h) or a dodge (d).
 */
public class DodgeballMain {
    /** input file name from which to read data */
    public static final String INPUT_FILENAME = "dodgeball.txt";

    /**
     * true for different results every run; false for
     * predictable results
     */
    public static final boolean RANDOM = false;

    /**
     * If not random, use this value to guide the sequence
     * of numbers that will be generated by the Random
     * object.
     */
    public static final int SEED = 99;
    
    
    public static int nThrowers;

    public static void main(String[] args)
            throws FileNotFoundException {
        // read names into Sets to eliminate duplicates
        File inputFile = new File(INPUT_FILENAME);
        if (!inputFile.canRead()) {
            System.out.println(
                    "Required input file not found; exiting.\n"
                            + inputFile.getAbsolutePath());
            System.exit(1);
        }
        Scanner input = new Scanner(inputFile);
        
        List<String> names = new LinkedList<String>();
        
        while (input.hasNextLine()) {
        	names.add(input.nextLine().strip());
        }
        input.close();

        Random rand = RANDOM ? new Random()
                : new Random(SEED);
        
        nThrowers = rand.nextInt(names.size()-2) +1;
        List<String> throwers = new LinkedList<String>();
        List<String> dodgers = new LinkedList<String>();

        //partition list into throwers and dodgers
        int i = 0;
        for(String s : names) {
        	if (i < nThrowers) {
        		throwers.add(s);
                //System.out.println("throwers initializes: " + s);
        	} else {
        		dodgers.add(s);
                //System.out.println("dodgers initializes: " + s);
        	}
        	i++;
        }
        
        
        DodgeballManager manager = new DodgeballManager(throwers, dodgers);

        // prompt the user for actions until the target score is reached
        Scanner console = new Scanner(System.in);
        while (manager.nActiveDodgers() > 0) {
            oneThrow(console, manager);
        }

        // report the winner(s)
        System.out.print(
                "MVP(s): ");
        manager.printMVP(System.out);
        System.out.println();
        
        // report sorted scores (BONUS)
        System.out.println();
        System.out.println("All scores, in order:");
        manager.printSortedScores(System.out);
    }

   
	/**
     * Handles the details of handling one throw.
     * Shows the current dodgeball positions,
     * prompts the user for a thrower name,
     * prompts the user for a target,
     * then prompts the user for whether the throw was a hit or a dodge
     */
    public static void oneThrow(Scanner console,
            DodgeballManager manager) {
        // print both linked lists
        System.out.print("Throwers: ");
        manager.printThrowers(System.out);
        System.out.println();
        System.out.print("Dodgers: ");
        manager.printDodgers(System.out);
        System.out.println();
        System.out.print("Bench: ");
        manager.printBench(System.out);
        
        // prompt for thrower
        System.out.println();
        System.out.print("Thrower name? ");
        String throwerName = console.nextLine().trim();
        while(!manager.isThrower(throwerName))
        {
        	System.out.println("Not a thrower.");
        	System.out.println();
            System.out.print("Thrower name? ");
            throwerName = console.nextLine().trim();
        }
        
        //prompt for Target
        System.out.println();
        System.out.print("Target name? ");
        String targetName = console.nextLine().trim();
        while(!manager.isActiveDodger(targetName))
        {
        	System.out.println("Not an active dodger.");
        	System.out.println();
            System.out.print("Target name? ");
            targetName = console.nextLine().trim();
        }
       
        //prompt for hit/dodge/catch
        System.out.println();
        System.out.print("Was it a hit (h), dodge (d), or catch (c)? ");
        String choice = console.nextLine().trim().toLowerCase();
        
        //handle the hit or dodge
        if (choice.startsWith("h")) {
            manager.hit(throwerName, targetName);
        } else if (choice.startsWith("d")) {
            manager.dodge(throwerName, targetName);
        } else if (choice.startsWith("c")) {
            System.out.println();
            if(manager.nBenchedPlayers() > 0) {
                System.out.print("Which benched player will be brought back? ");
                String benchBackName = console.nextLine().trim();
                while(!manager.isBenchedPlayer(benchBackName)) {
                    System.out.println("Not a benched dodger.");
                    System.out.println();
                    System.out.print("Which benched player will be brought back? ");
                    benchBackName = console.nextLine().trim();
                }
                manager.catchBall(throwerName, targetName, benchBackName);
            } else {
                manager.catchBall(throwerName, targetName);
            }
            
        } else {
        	System.out.println("Could not recognize action '" + choice + "'" );
        }
        System.out.println();
    }

}
